### PR TITLE
Upgraded SSM to 4.1.1

### PR DESCRIPTION
**Pull request by Lantzify**
Upgrading SSM to 4.1.1 fixed issue #16

### CODE REVIEW

**Review by mattbrailsford — CHANGES_REQUESTED** [review]
Could you please move the last commit to another PR? These don't unfortunately relate to the PR at hand "Upgrade SSM"

**Comment by Lantzify** [comment]
Sorry about that!

**Comment by mattbrailsford** [comment]
Can you confirm if the script tag renders ok? I've generally had problems in the past with URL's that contain the `@` symbol given this is a reserved symbol. It often needs escaping.

**Comment by Lantzify** [comment]
Yes! It renders ok! I have had the same issue in the past. But now it seems to work fine!

Capture

**Pull request merged**
