### PR TITLE
Use dictionary for all hardcoded strings in views

### PR DESCRIPTION
**Pull request by JasonElkin**
This adds internationalisation to views by way of the Umbraco dictionary.

### CODE REVIEW

**Comment by mattbrailsford** [comment]
Looks really good. Thanks for doing the conversion 👍

**Comment by mattbrailsford** [comment]
Could probably do with checking to see if dictionary items can be used in email templates too

**Comment by JasonElkin** [comment]
Thanks @mattbrailsford 

I'm pretty sure they can be used, if not by way of an Umbraco helper it's trivial to inject the factory. That said, I did have a look at the emails but I wasn't sure that it would work so well with dictionary items as in places they contain what I would consider "content", unlike the more straightforward UI strings in the checkout.  The client I'm working with needs extra content in those emails too, and I imagine that's a common scenario.

As Vendr has a UI to change the email paths I'm currently opting to duplicate the email templates modify the razor directly.

**Comment by JasonElkin** [comment]
IMHO the best option would be to surface some RTEs in the Backoffice, with the ability to set placeholders, for the more "contenty" parts of the emails (like the below). Then could use the dictionary for the rest.
```
<p>
    There is a problem with your payment for order <strong>@Model.OrderNumber</strong>.
</p>
<p>
    Please contact us by replying to this email at your earliest convenience.
</p>
<p class="margin: 0;">
    Your order will not be shipped until this problem has been resolved.
</p>
```

**Comment by mattbrailsford** [comment]
Yea, I'll add it to me list to test. An yea, the email templates can be replaced so not as big a deal, but would still be nice to round them all off.

Thanks for sorting out the main templates though. I've already copied the updates to the v2 branch 👍

**Comment by mattbrailsford** [comment]
> IMHO the best option would be to surface some RTEs in the Backoffice, with the ability to set placeholders, for the more "contenty" parts of the emails (like the below). Then could use the dictionary for the rest.

Yea, it's a shame the Umbraco Dictionary section can't handle more than just simple strings.

**Pull request merged**
